TickerList:                             
  -
    TickerIndex: 0
    Ticker: ag2412
    ExchangeID: SHFE
    PriceTick: 1
    
  -
    TickerIndex: 1
    Ticker: ag2501
    ExchangeID: SHFE
    PriceTick: 1