TickerList:                             
  -
    TickerIndex: 0
    Ticker: ag2606
    ExchangeID: SHFE
    PriceTick: 1
    
  -
    TickerIndex: 1
    Ticker: ag2609
    ExchangeID: SHFE
    PriceTick: 1

  -
    TickerIndex: 2
    Ticker: al2606
    ExchangeID: SHFE
    PriceTick: 1

  -
    TickerIndex: 3
    Ticker: al2609
    ExchangeID: SHFE
    PriceTick: 1

  -
    TickerIndex: 4
    Ticker: au2606
    ExchangeID: SHFE
    PriceTick: 1

  -
    TickerIndex: 5
    Ticker: au2609
    ExchangeID: SHFE
    PriceTick: 1

  -
    TickerIndex: 6
    Ticker: cu2606
    ExchangeID: SHFE
    PriceTick: 1

  -
    TickerIndex: 7
    Ticker: cu2609
    ExchangeID: SHFE
    PriceTick: 1

  -
    TickerIndex: 8
    Ticker: rb2606
    ExchangeID: SHFE
    PriceTick: 1

  -
    TickerIndex: 9
    Ticker: rb2609
    ExchangeID: SHFE
    PriceTick: 1

  -
    TickerIndex: 10
    Ticker: sc2606
    ExchangeID: SHFE
    PriceTick: 1
    
  -
    TickerIndex: 11
    Ticker: sc2609
    ExchangeID: SHFE
    PriceTick: 1